name: Caching envs

on:
  workflow_dispatch

jobs:
  per-docs-write:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true
      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: docs-cache
        id: cache
      - name: Update environment
        run:
          mamba env update -n anaconda-client-env -f ./environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Look at python
        shell: bash -l {0}
        run: |
          python --version

  per-docs-read:  
    needs: per-docs-write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true
      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: docs-cache
        id: cache
      - name: Update environment
        run:
          mamba env update -n anaconda-client-env -f ./environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Look at python
        shell: bash -l {0}
        run: |
          python --version

  careful-cache-write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Look for cache
        id: look-for-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
          lookup-only: true
      - name: Setup empty Mambaforge
        if: steps.look-for-cache.outputs.cache-hit == 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env-CAREFUL
          use-mamba: true
      - name: Load cache
        if: steps.look-for-cache.outputs.cache-hit == 'true'
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
      - name: Setup Mambaforge with env file
        if: steps.look-for-cache.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env-CAREFUL
          use-mamba: true
          environment-file: ./environment.yml
      - name: Save cache
        if: steps.look-for-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
      - name: Look at python
        shell: bash -l {0}
        run: |
          python --version

  careful-cache-read:
    needs: careful-cache-write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Look for cache
        id: look-for-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
          lookup-only: true
      - name: Setup empty Mambaforge
        if: steps.look-for-cache.outputs.cache-hit == 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env-CAREFUL
          use-mamba: true
      - name: Load cache
        if: steps.look-for-cache.outputs.cache-hit == 'true'
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
      - name: Setup Mambaforge with env file
        if: steps.look-for-cache.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env-CAREFUL
          use-mamba: true
          environment-file: ./environment.yml
      - name: Save cache
        if: steps.look-for-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ env.CONDA }}/envs
          key: careful-cache
      - name: Look at python
        shell: bash -l {0}
        run: |
          python --version
