name: Caching envs

on:
  workflow_dispatch

jobs:
  per-docs:  
  # Just the [docs example](https://github.com/conda-incubator/setup-miniconda?tab=readme-ov-file#caching-environments)
  # With a particular (python-version-containing) env file and a specific version request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.9'
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true
      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('./environment.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache
      - name: Update environment
        run:
          mamba env update -n anaconda-client-env -f ./environment.yml
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Look at python
        shell: bash -l {0}
        run: |
          python --version
